package com.layerlab.backend.property;

import com.layerlab.backend.entity.Role;
import com.layerlab.backend.entity.User;
import com.layerlab.backend.exception.UnprocessableEntityException;
import com.layerlab.backend.repository.UserRepository;
import com.layerlab.backend.security.JwtUtil;
import com.layerlab.backend.service.EmailService;
import com.layerlab.backend.service.TwoFactorServiceImpl;
import net.jqwik.api.*;
import net.jqwik.api.constraints.IntRange;
import net.jqwik.api.constraints.StringLength;
import org.junit.jupiter.api.Tag;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import java.lang.reflect.Field;
import java.time.LocalDateTime;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicReference;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Property-based tests for OTP validity and single-use guarantee (Property 12).
 *
 * <p>Validates: Requirement 16.4
 *
 * <p>Property 12: For every OTP generated by {@code TwoFactorService}:
 * <ul>
 *   <li>The code is valid immediately after generation.</li>
 *   <li>The code is invalid (rejected with HTTP 422) after 10 minutes.</li>
 *   <li>The code can only be used once — a second validation attempt is rejected.</li>
 * </ul>
 *
 * <p>Note: {@link EmailService} is a concrete Spring {@code @Service} class that requires a
 * {@link org.springframework.mail.javamail.JavaMailSender} at construction time. To avoid
 * Mockito's Byte Buddy limitations on Java 25 (which prevent mocking concrete classes via
 * inline instrumentation), we use a hand-written anonymous stub that captures the OTP sent
 * via {@code sendOtpEmail} without touching the mail infrastructure.
 */
@Tag("Feature: layerlab-backend, Property 12: Validité et unicité du code OTP")
class OtpPropertyTest {

    private static final String JWT_SECRET =
            "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970";
    private static final long JWT_EXPIRATION_MS = 86_400_000L; // 24 h

    // -------------------------------------------------------------------------
    // Stub: EmailService
    // -------------------------------------------------------------------------

    /**
     * Hand-written stub for {@link EmailService}.
     *
     * <p>Bypasses the need for a real {@link org.springframework.mail.javamail.JavaMailSender}
     * and avoids Mockito's Byte Buddy instrumentation issues on Java 25.
     * The last OTP sent is stored in {@link #lastOtp} for assertion.
     */
    private static class CapturingEmailServiceStub extends EmailService {

        /** The most recent raw OTP passed to {@code sendOtpEmail}. */
        volatile String lastOtp;

        CapturingEmailServiceStub() {
            // EmailService requires a JavaMailSender — pass null since we override the method.
            super(null);
        }

        @Override
        public void sendOtpEmail(String to, String otpCode) {
            this.lastOtp = otpCode;
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Creates a {@link JwtUtil} with the test secret and a 24-hour expiration.
     */
    private JwtUtil createJwtUtil() throws Exception {
        JwtUtil jwtUtil = new JwtUtil();

        Field secretField = JwtUtil.class.getDeclaredField("secret");
        secretField.setAccessible(true);
        secretField.set(jwtUtil, JWT_SECRET);

        Field expirationField = JwtUtil.class.getDeclaredField("expirationMs");
        expirationField.setAccessible(true);
        expirationField.set(jwtUtil, JWT_EXPIRATION_MS);

        return jwtUtil;
    }

    /**
     * Builds a minimal {@link User} with the given id and email, no pending OTP.
     */
    private User buildUser(long id, String email) {
        User user = new User();
        user.setId(id);
        user.setFirstName("Test");
        user.setLastName("User");
        user.setEmail(email);
        user.setPassword("hashed-password");
        user.setRole(Role.ROLE_USER);
        user.setActive(true);
        user.setTwoFactorEnabled(true);
        user.setOtpCode(null);
        user.setOtpExpiry(null);
        return user;
    }

    /**
     * Creates a {@link UserRepository} mock (interface — safe to mock on Java 25)
     * pre-configured to return {@code user} for {@code findById} and echo saves.
     */
    private UserRepository buildUserRepositoryMock(User user) {
        UserRepository repo = mock(UserRepository.class);
        when(repo.findById(user.getId())).thenReturn(Optional.of(user));
        when(repo.save(any(User.class))).thenAnswer(inv -> inv.getArgument(0));
        return repo;
    }

    // -------------------------------------------------------------------------
    // Property A — OTP is valid immediately after generation
    // -------------------------------------------------------------------------

    /**
     * Property A — Immediate validity:
     * For any user ID and email, an OTP generated by {@code generateOtp} must be
     * accepted by {@code validateOtp} when submitted immediately (before expiry).
     *
     * <p>Validates: Requirement 16.4
     */
    @Property(tries = 100)
    void otpIsValidImmediatelyAfterGeneration(
            @ForAll @IntRange(min = 1, max = 10_000) int userId,
            @ForAll @net.jqwik.api.constraints.AlphaChars
            @StringLength(min = 1, max = 20) String localPart
    ) throws Exception {
        String email = localPart + "@test.com";
        long uid = userId;

        User user = buildUser(uid, email);
        UserRepository userRepository = buildUserRepositoryMock(user);
        CapturingEmailServiceStub emailStub = new CapturingEmailServiceStub();
        JwtUtil jwtUtil = createJwtUtil();

        TwoFactorServiceImpl service = new TwoFactorServiceImpl(userRepository, emailStub, jwtUtil);

        // --- generate OTP ---
        service.generateOtp(uid);

        String rawOtp = emailStub.lastOtp;
        assert rawOtp != null : "EmailService.sendOtpEmail must have been called";
        assert rawOtp.matches("\\d{6}") : "OTP must be exactly 6 digits, got: " + rawOtp;

        // The user object is mutated in-place by the service (save mock returns same instance)
        assert user.getOtpCode() != null : "otpCode must be set after generateOtp";
        assert user.getOtpExpiry() != null : "otpExpiry must be set after generateOtp";
        assert user.getOtpExpiry().isAfter(LocalDateTime.now())
                : "otpExpiry must be in the future immediately after generation";

        // --- validate OTP immediately ---
        String token = service.validateOtp(uid, rawOtp);

        assert token != null && !token.isBlank()
                : "validateOtp must return a non-blank JWT token for a valid OTP";

        // After successful validation the OTP must be cleared (single-use)
        assert user.getOtpCode() == null
                : "otpCode must be cleared after successful validation";
        assert user.getOtpExpiry() == null
                : "otpExpiry must be cleared after successful validation";
    }

    // -------------------------------------------------------------------------
    // Property B — OTP is invalid after expiry
    // -------------------------------------------------------------------------

    /**
     * Property B — Post-expiry invalidity:
     * For any user ID and email, an OTP whose expiry has already passed must be
     * rejected by {@code validateOtp} with an {@link UnprocessableEntityException}.
     *
     * <p>The expiry is simulated by directly setting {@code otpExpiry} to a past
     * timestamp on the user object before calling {@code validateOtp}.
     *
     * <p>Validates: Requirement 16.4
     */
    @Property(tries = 100)
    void otpIsInvalidAfterExpiry(
            @ForAll @IntRange(min = 1, max = 10_000) int userId,
            @ForAll @net.jqwik.api.constraints.AlphaChars
            @StringLength(min = 1, max = 20) String localPart,
            @ForAll @IntRange(min = 1, max = 600) int minutesExpired
    ) throws Exception {
        String email = localPart + "@test.com";
        long uid = userId;

        // Build a user that already has an OTP but with an expired timestamp
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        String rawOtp = String.format("%06d", userId % 1_000_000);
        String hashedOtp = encoder.encode(rawOtp);
        LocalDateTime expiredAt = LocalDateTime.now().minusMinutes(minutesExpired);

        User user = buildUser(uid, email);
        user.setOtpCode(hashedOtp);
        user.setOtpExpiry(expiredAt);

        UserRepository userRepository = buildUserRepositoryMock(user);
        CapturingEmailServiceStub emailStub = new CapturingEmailServiceStub();
        JwtUtil jwtUtil = createJwtUtil();

        TwoFactorServiceImpl service = new TwoFactorServiceImpl(userRepository, emailStub, jwtUtil);

        // --- attempt to validate the expired OTP ---
        boolean exceptionThrown = false;
        try {
            service.validateOtp(uid, rawOtp);
        } catch (UnprocessableEntityException e) {
            exceptionThrown = true;
            assert e.getMessage() != null && !e.getMessage().isBlank()
                    : "Exception message must not be blank for expired OTP";
        }

        assert exceptionThrown
                : "validateOtp must throw UnprocessableEntityException for an expired OTP "
                + "(expired " + minutesExpired + " minutes ago)";

        // After expiry rejection the OTP must be cleared
        assert user.getOtpCode() == null
                : "otpCode must be cleared after expiry rejection";
        assert user.getOtpExpiry() == null
                : "otpExpiry must be cleared after expiry rejection";
    }

    // -------------------------------------------------------------------------
    // Property C — OTP can only be used once (single-use guarantee)
    // -------------------------------------------------------------------------

    /**
     * Property C — Single-use guarantee:
     * For any user ID and email, after a successful first validation of an OTP,
     * a second call to {@code validateOtp} with the same code must be rejected
     * with an {@link UnprocessableEntityException} (no pending OTP).
     *
     * <p>Validates: Requirement 16.4
     */
    @Property(tries = 100)
    void otpCanOnlyBeUsedOnce(
            @ForAll @IntRange(min = 1, max = 10_000) int userId,
            @ForAll @net.jqwik.api.constraints.AlphaChars
            @StringLength(min = 1, max = 20) String localPart
    ) throws Exception {
        String email = localPart + "@test.com";
        long uid = userId;

        User user = buildUser(uid, email);
        UserRepository userRepository = buildUserRepositoryMock(user);
        CapturingEmailServiceStub emailStub = new CapturingEmailServiceStub();
        JwtUtil jwtUtil = createJwtUtil();

        TwoFactorServiceImpl service = new TwoFactorServiceImpl(userRepository, emailStub, jwtUtil);

        // --- generate OTP ---
        service.generateOtp(uid);
        String rawOtp = emailStub.lastOtp;
        assert rawOtp != null : "OTP must have been captured";

        // --- first validation: must succeed ---
        String token = service.validateOtp(uid, rawOtp);
        assert token != null && !token.isBlank()
                : "First validateOtp call must return a valid JWT token";

        // OTP is now cleared on the user object
        assert user.getOtpCode() == null : "otpCode must be null after first use";
        assert user.getOtpExpiry() == null : "otpExpiry must be null after first use";

        // --- second validation with the same code: must fail ---
        boolean exceptionThrown = false;
        try {
            service.validateOtp(uid, rawOtp);
        } catch (UnprocessableEntityException e) {
            exceptionThrown = true;
            assert e.getMessage() != null && !e.getMessage().isBlank()
                    : "Exception message must not be blank for reused OTP";
        }

        assert exceptionThrown
                : "validateOtp must throw UnprocessableEntityException when the OTP has already been used";
    }

    // -------------------------------------------------------------------------
    // Property D — OTP format is always exactly 6 digits
    // -------------------------------------------------------------------------

    /**
     * Property D — OTP format:
     * For any user ID and email, the OTP sent by {@code generateOtp} must always
     * be a string of exactly 6 decimal digits (zero-padded if necessary).
     *
     * <p>Validates: Requirement 16.4
     */
    @Property(tries = 100)
    void otpIsAlwaysSixDigits(
            @ForAll @IntRange(min = 1, max = 10_000) int userId,
            @ForAll @net.jqwik.api.constraints.AlphaChars
            @StringLength(min = 1, max = 20) String localPart
    ) throws Exception {
        String email = localPart + "@test.com";
        long uid = userId;

        User user = buildUser(uid, email);
        UserRepository userRepository = buildUserRepositoryMock(user);
        CapturingEmailServiceStub emailStub = new CapturingEmailServiceStub();
        JwtUtil jwtUtil = createJwtUtil();

        TwoFactorServiceImpl service = new TwoFactorServiceImpl(userRepository, emailStub, jwtUtil);

        // --- generate OTP ---
        service.generateOtp(uid);

        String rawOtp = emailStub.lastOtp;
        assert rawOtp != null : "OTP must have been sent via EmailService";
        assert rawOtp.length() == 6
                : "OTP must be exactly 6 characters long, got length " + rawOtp.length() + ": " + rawOtp;
        assert rawOtp.matches("\\d{6}")
                : "OTP must consist of exactly 6 decimal digits, got: " + rawOtp;
    }

    // -------------------------------------------------------------------------
    // Property E — Invalid OTP code is rejected without clearing a valid pending OTP
    // -------------------------------------------------------------------------

    /**
     * Property E — Wrong code rejection:
     * For any user with a valid pending OTP, submitting an incorrect code must be
     * rejected with {@link UnprocessableEntityException} and the pending OTP must
     * remain intact (not cleared), so the user can retry with the correct code.
     *
     * <p>Validates: Requirement 16.4
     */
    @Property(tries = 100)
    void wrongOtpCodeIsRejectedAndPendingOtpIsPreserved(
            @ForAll @IntRange(min = 1, max = 10_000) int userId,
            @ForAll @net.jqwik.api.constraints.AlphaChars
            @StringLength(min = 1, max = 20) String localPart
    ) throws Exception {
        String email = localPart + "@test.com";
        long uid = userId;

        // Pre-load user with a known valid OTP (not expired)
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        String correctOtp = "123456";
        String hashedOtp = encoder.encode(correctOtp);
        LocalDateTime futureExpiry = LocalDateTime.now().plusMinutes(10);

        User user = buildUser(uid, email);
        user.setOtpCode(hashedOtp);
        user.setOtpExpiry(futureExpiry);

        UserRepository userRepository = buildUserRepositoryMock(user);
        CapturingEmailServiceStub emailStub = new CapturingEmailServiceStub();
        JwtUtil jwtUtil = createJwtUtil();

        TwoFactorServiceImpl service = new TwoFactorServiceImpl(userRepository, emailStub, jwtUtil);

        // Submit a wrong code (guaranteed different from correctOtp)
        String wrongOtp = "000000".equals(correctOtp) ? "111111" : "000000";

        boolean exceptionThrown = false;
        try {
            service.validateOtp(uid, wrongOtp);
        } catch (UnprocessableEntityException e) {
            exceptionThrown = true;
        }

        assert exceptionThrown
                : "validateOtp must throw UnprocessableEntityException for a wrong OTP code";

        // The pending OTP must NOT be cleared — the user should be able to retry
        assert user.getOtpCode() != null
                : "otpCode must remain set after a wrong-code rejection";
        assert user.getOtpExpiry() != null
                : "otpExpiry must remain set after a wrong-code rejection";
    }
}
